CC=g++
CFLAGS=-Wall -O3
BINS=solGreedyAleatorio
all: clean problema

problema:
	$(CC) $(CFLAGS) -o $(BINS) solGreedyAleatorio.cpp

clean:
	@echo " [CLN] Removing binary files"
	@rm -f $(BINS)
